/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panel;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author halo
 */
public class PasswordPanel extends SuperPanels
{
    JTextField userField = new JTextField();
    JPasswordField passField = new JPasswordField();
    JButton ok = new JButton("Login");
    ActionListener listenerForOKButton;
    public PasswordPanel() {
        super();
        //initComponents();
	JLabel user = new JLabel("UserID");
	JLabel password = new JLabel("Password");		
		user.setBounds		(50, 0 , 300, 50);
		password.setBounds	(50,100, 300, 50);
		userField.setBounds	(50, 50, 300, 50);
		passField.setBounds	(50,150, 300, 50);
		ok.setBounds		(50,200, 300, 50);
		//add(user);
		add(password);
		//add(userField);
		add(passField);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void addListener(ActionListener listener)
    {
        
    }
    public void setPassword(String password)	
    {
        passField.setText(password);
    }
    public String getPassword()
    {
        return passField.getText();
    }
}
