/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Tuk
 */
public class VWithdraw extends javax.swing.JFrame {

    /**
     * Creates new form VWithdraw
     */
    public VWithdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        No3 = new javax.swing.JButton();
        No5 = new javax.swing.JButton();
        No8 = new javax.swing.JButton();
        No0 = new javax.swing.JButton();
        reSet = new javax.swing.JButton();
        No6 = new javax.swing.JButton();
        No9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        No4 = new javax.swing.JButton();
        No1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Transfer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ent = new javax.swing.JButton();
        Del = new javax.swing.JButton();
        No7 = new javax.swing.JButton();
        No2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        No3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/3.jpg"))); // NOI18N
        No3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No3ActionPerformed(evt);
            }
        });
        getContentPane().add(No3);
        No3.setBounds(457, 188, 144, 75);

        No5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/5.jpg"))); // NOI18N
        No5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No5ActionPerformed(evt);
            }
        });
        getContentPane().add(No5);
        No5.setBounds(303, 269, 144, 75);

        No8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/8.jpg"))); // NOI18N
        No8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No8ActionPerformed(evt);
            }
        });
        getContentPane().add(No8);
        No8.setBounds(303, 355, 144, 72);

        No0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/0.jpg"))); // NOI18N
        No0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No0ActionPerformed(evt);
            }
        });
        getContentPane().add(No0);
        No0.setBounds(303, 433, 144, 75);

        reSet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Reset.jpg"))); // NOI18N
        reSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reSetActionPerformed(evt);
            }
        });
        getContentPane().add(reSet);
        reSet.setBounds(153, 433, 144, 75);

        No6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/6.jpg"))); // NOI18N
        No6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No6ActionPerformed(evt);
            }
        });
        getContentPane().add(No6);
        No6.setBounds(457, 269, 144, 75);

        No9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/9.jpg"))); // NOI18N
        No9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No9ActionPerformed(evt);
            }
        });
        getContentPane().add(No9);
        No9.setBounds(457, 355, 144, 72);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(153, 110, 448, 67);

        No4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/4.jpg"))); // NOI18N
        No4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No4ActionPerformed(evt);
            }
        });
        getContentPane().add(No4);
        No4.setBounds(153, 269, 144, 75);

        No1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/1.jpg"))); // NOI18N
        No1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No1ActionPerformed(evt);
            }
        });
        getContentPane().add(No1);
        No1.setBounds(153, 188, 144, 75);

        jPanel1.setLayout(null);

        Transfer.setBackground(new java.awt.Color(0, 204, 51));
        Transfer.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Transfer.setForeground(new java.awt.Color(255, 255, 51));
        Transfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Transfer.setText("Withdraw");
        Transfer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Transfer.setOpaque(true);
        jPanel1.add(Transfer);
        Transfer.setBounds(270, 10, 220, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/DDDDDDDD.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 104);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("B.");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(619, 110, 49, 67);

        ent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Enter.jpg"))); // NOI18N
        ent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entActionPerformed(evt);
            }
        });
        getContentPane().add(ent);
        ent.setBounds(305, 514, 142, 75);

        Del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.jpg"))); // NOI18N
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });
        getContentPane().add(Del);
        Del.setBounds(457, 433, 144, 75);

        No7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/7.jpg"))); // NOI18N
        No7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No7ActionPerformed(evt);
            }
        });
        getContentPane().add(No7);
        No7.setBounds(153, 355, 144, 72);

        No2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        No2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/2.jpg"))); // NOI18N
        No2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No2ActionPerformed(evt);
            }
        });
        getContentPane().add(No2);
        No2.setBounds(303, 188, 144, 75);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No3ActionPerformed
        //des2.setText(des2.getText()+3);
    }//GEN-LAST:event_No3ActionPerformed

    private void No5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No5ActionPerformed
        //des2.setText(des2.getText()+5);
    }//GEN-LAST:event_No5ActionPerformed

    private void No8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No8ActionPerformed
        //des2.setText(des2.getText()+8);
    }//GEN-LAST:event_No8ActionPerformed

    private void No0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No0ActionPerformed
        //des2.setText(des2.getText()+0);
    }//GEN-LAST:event_No0ActionPerformed

    private void reSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reSetActionPerformed
        //des2.setText("");
    }//GEN-LAST:event_reSetActionPerformed

    private void No6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No6ActionPerformed
        //des2.setText(des2.getText()+6);
    }//GEN-LAST:event_No6ActionPerformed

    private void No9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No9ActionPerformed
        //des2.setText(des2.getText()+9);
    }//GEN-LAST:event_No9ActionPerformed

    private void No4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No4ActionPerformed
        //des2.setText(des2.getText()+4);
    }//GEN-LAST:event_No4ActionPerformed

    private void No1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No1ActionPerformed
        //des2.setText(des2.getText()+1);
    }//GEN-LAST:event_No1ActionPerformed

    private void entActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entActionPerformed
        /*int num1 = Integer.parseInt(storeData.balance); // set balance(String) convert to nums(int)
        int num2 = 0; // set num2 = 0
        int change;
        if(des2.getText().length()>=1 && des2.getText().length()<=10) { // des2 must have 1 to 10 length
            num2 = Integer.parseInt(des2.getText());      // because int can get 10 digit of number (or) billion
            // get des2(text) text to num2
        } else if(des2.getText().length() > 10) { // des2 length more than 10
            JOptionPane.showMessageDialog(null, "It's too much AMOUNT!!");
            des2.setText("");
        }

        if(num2==0) { // num2 equal 0 (or) num2 isn't declared by des2(text)
            JOptionPane.showMessageDialog(null, "Please insert MONEY!!");
            des2.setText("");
        } else if(num2 <= 100000) { // num2 must lower equal 100,000
            if(num2>0 && (num2%20==0||num2%50==0||num2%70==0)) { // if num2 inform of BANKNOTE 70 = 50 + 20
                change = num2+ num1;
                storeData.balance = Integer.toString(change);
                getDB.updateDB();
                getDB.updateStatement_De(des2.getText());
                JOptionPane.showMessageDialog(null, "\nID : "+storeData.user+"\n"
                    + "\nName : "+storeData.name+"\n"
                    + "\nMode : Deposit\n"
                    + "\nAmount : " + num2 +"\n"
                    + "\nBalance : " + storeData.balance +"\n");
                in.setVisible(true);
                this.dispose();
            } else if(!(num2%20==0||num2%50==0||num2%70==0)){ // if NOT BANKNOTE!!
                JOptionPane.showMessageDialog(null, "Plese insert correct money in the form of BANKNOTE!!");
                des2.setText("");
            }
        } else { // more than 100,000 about(100,001 to billion)
            JOptionPane.showMessageDialog(null, "Cannot insert AMOUNT more than 100,000 Baht!!");
            des2.setText("");
        }*/
    }//GEN-LAST:event_entActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        /*String s = des2.getText();
        if(s.length()>=1) {
            des2.setText(s.substring(0,s.length()-1));
        }*/
    }//GEN-LAST:event_DelActionPerformed

    private void No7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No7ActionPerformed
        //des2.setText(des2.getText()+7);
    }//GEN-LAST:event_No7ActionPerformed

    private void No2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No2ActionPerformed
        //des2.setText(des2.getText()+2);
    }//GEN-LAST:event_No2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VWithdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del;
    private javax.swing.JButton No0;
    private javax.swing.JButton No1;
    private javax.swing.JButton No2;
    private javax.swing.JButton No3;
    private javax.swing.JButton No4;
    private javax.swing.JButton No5;
    private javax.swing.JButton No6;
    private javax.swing.JButton No7;
    private javax.swing.JButton No8;
    private javax.swing.JButton No9;
    private javax.swing.JLabel Transfer;
    private javax.swing.JButton ent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reSet;
    // End of variables declaration//GEN-END:variables
}
